-- MySQL Script generated by MySQL Workbench
-- vie 13 nov 2020 19:08:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `idBloque` INT NOT NULL AUTO_INCREMENT,
  `Bloquecol` VARCHAR(45) NULL,
  `idConstruccion` INT NOT NULL,
  PRIMARY KEY (`idBloque`),
  INDEX `construcion_idx` (`idConstruccion` ASC) VISIBLE,
  UNIQUE INDEX `idConstruccion_UNIQUE` (`idConstruccion` ASC) VISIBLE,
  CONSTRAINT `construcion`
    FOREIGN KEY (`idConstruccion`)
    REFERENCES `mydb`.`Construcción` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Carriles` INT NULL,
  `Longitud` INT NULL,
  `Zona` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`),
  UNIQUE INDEX `Zona_UNIQUE` (`Zona` ASC) VISIBLE,
  CONSTRAINT `zona`
    FOREIGN KEY (`Zona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Construcción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Construcción` (
  `Numero` INT NOT NULL,
  `CoordenadaGeografica` VARCHAR(45) NOT NULL,
  `Superficie` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  UNIQUE INDEX `CoordenadaGeografica_UNIQUE` (`CoordenadaGeografica` ASC) VISIBLE,
  INDEX `calle_idx` (`calle` ASC) VISIBLE,
  PRIMARY KEY (`Numero`),
  UNIQUE INDEX `Unifamiliar_UNIQUE` () VISIBLE,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`Calle` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` VARCHAR(9) NOT NULL,
  `Fecha_nacimiento` DATE NULL,
  `Estudios` VARCHAR(45) NULL,
  `Nombre` VARCHAR(20) NULL,
  `Cabeza_familia` VARCHAR(9) NOT NULL,
  `vivienda` INT NULL,
  `tipoVivienda` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `Cabeza_familia_idx` (`Cabeza_familia` ASC) VISIBLE,
  INDEX `unifamiliar_idx` (`vivienda` ASC) VISIBLE,
  CONSTRAINT `Cabeza_familia`
    FOREIGN KEY (`Cabeza_familia`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vivienda`
    FOREIGN KEY (`vivienda`)
    REFERENCES `mydb`.`Unifamiliar` (`idUnifamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vivienda`
    FOREIGN KEY (`vivienda`)
    REFERENCES `mydb`.`Piso` (`Planta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Superficie` INT NULL,
  `Letra` VARCHAR(1) NOT NULL,
  `Planta` INT NOT NULL,
  `bloque` INT NULL,
  `unifamiliar` INT NULL,
  INDEX `bloque_idx` (`bloque` ASC) VISIBLE,
  PRIMARY KEY (`Letra`, `Planta`),
  CONSTRAINT `bloque`
    FOREIGN KEY (`bloque`)
    REFERENCES `mydb`.`Bloque` (`idBloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unifamiliar` (
  `idUnifamiliar` INT GENERATED ALWAYS AS (),
  `Superficie` INT NULL,
  `NumeroHabitaciones` VARCHAR(45) NULL,
  `idConstruccion` INT NOT NULL,
  PRIMARY KEY (`idUnifamiliar`),
  INDEX `construccion_idx` (`idConstruccion` ASC) VISIBLE,
  UNIQUE INDEX `idConstruccion_UNIQUE` (`idConstruccion` ASC) VISIBLE,
  CONSTRAINT `construccion`
    FOREIGN KEY (`idConstruccion`)
    REFERENCES `mydb`.`Construcción` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Nombre` VARCHAR(45) GENERATED ALWAYS AS (),
  `Zona` VARCHAR(45) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `Concejal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  UNIQUE INDEX `Concejal_UNIQUE` (`Concejal` ASC) VISIBLE,
  UNIQUE INDEX `Ubicacion_UNIQUE` (`Ubicacion` ASC) VISIBLE,
  UNIQUE INDEX `Zona_UNIQUE` (`Zona` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
