-- MySQL Script generated by MySQL Workbench
-- vie 13 nov 2020 19:38:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vivero` (
  `ubicación_x` DECIMAL NOT NULL,
  `ubicacion_y` DECIMAL NOT NULL,
  `ID` INT NULL,
  `cierre` VARCHAR(45) NULL,
  `apertura` VARCHAR(45) NULL,
  PRIMARY KEY (`ubicación_x`, `ubicacion_y`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zona` (
  `n_zona` INT NOT NULL,
  `ubicación_x` DECIMAL NOT NULL,
  `ubicacion_y` DECIMAL NOT NULL,
  PRIMARY KEY (`n_zona`),
  INDEX `vivero_idx` (`ubicación_x` ASC, `ubicacion_y` ASC) VISIBLE,
  CONSTRAINT `vivero_x`
    FOREIGN KEY (`ubicación_x` , `ubicacion_y`)
    REFERENCES `mydb`.`vivero` (`ubicación_x` , `ubicacion_y`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descuento` INT NULL,
  `gasto mensual` INT NOT NULL,
  `fecha nacimiento` DATE NOT NULL,
  `codigo fidelizacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_idx` (`cliente` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `mydb`.`cliente` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `dni` INT NOT NULL,
  `seguridad_social` INT NOT NULL,
  `teléfono` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `pedido` INT NULL,
  PRIMARY KEY (`dni`, `seguridad_social`),
  INDEX `pedido_idx` (`pedido` ASC) VISIBLE,
  CONSTRAINT `pedido`
    FOREIGN KEY (`pedido`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `codigo de barras` INT NOT NULL,
  `stock` INT NOT NULL,
  `Precio` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `caducidad` DATE NULL,
  PRIMARY KEY (`codigo de barras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zona_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zona_producto` (
  `producto` INT NOT NULL,
  `zona` INT NOT NULL,
  `stock` INT NOT NULL,
  UNIQUE INDEX `stock_UNIQUE` (`stock` ASC) VISIBLE,
  PRIMARY KEY (`producto`, `zona`),
  INDEX `zona_idx` (`zona` ASC) VISIBLE,
  CONSTRAINT `zona`
    FOREIGN KEY (`zona`)
    REFERENCES `mydb`.`zona` (`n_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto`
    FOREIGN KEY (`producto`)
    REFERENCES `mydb`.`producto` (`codigo de barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zona_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zona_empleado` (
  `n_zona` INT NOT NULL,
  `empleado_dni` INT NOT NULL,
  `empleado_seguridad_social` INT NOT NULL,
  `fecha_ini` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  PRIMARY KEY (`n_zona`, `empleado_dni`, `empleado_seguridad_social`),
  INDEX `fk_zona_has_empleado_empleado1_idx` (`empleado_dni` ASC, `empleado_seguridad_social` ASC) VISIBLE,
  INDEX `fk_zona_has_empleado_zona1_idx` (`n_zona` ASC) VISIBLE,
  CONSTRAINT `zona`
    FOREIGN KEY (`n_zona`)
    REFERENCES `mydb`.`zona` (`n_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado`
    FOREIGN KEY (`empleado_dni` , `empleado_seguridad_social`)
    REFERENCES `mydb`.`empleado` (`dni` , `seguridad_social`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto_pedido` (
  `codigo` INT NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`, `id`),
  INDEX `pedido_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `pedido`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`pedido` (`cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto`
    FOREIGN KEY (`codigo`)
    REFERENCES `mydb`.`producto` (`codigo de barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
